### ISSUE TITLE
Module Blockchain didn't work ?

### ISSUE THREAD

**Issue by DocKali** [InQuest/omnibus#15]
Hi,
I'm currently testing your tool and it seems really powerful, thanks for your work. 

When I try to run the Blockchain module, it seems there is an error. I have the following output from Omnibus : 
omnibus >> blockchain 2
[!] Unknown command

Artifact 2 is a blockchain adress.

Thanks for your help!

**Comment by deadbits** [comment]
This has been fixed by commit https://github.com/InQuest/omnibus/commit/ab2d62a11ae3fc74b4ae175c36e880fb34c22d4f

The cli was missing the actual function needed to call the blockchain module. Though in adding that I found there's a bug where Blockchain addresses are being stored as usernames - the blockchain module will still work but it's unfortunately being stored in the 'user' MongoDB collection. I'll get a fix out for this ASAP as well

**Comment by DocKali** [comment]
Thank you for your work. Let's go for a git pull and wait for your fix concerning storage of Bitcoin adresses.
